services:
  dotnet:
    image: linkdotnet.blog.web
    build: ./
    container_name: dotnetBlog
    ports:
      - 1234:1234 #You can modify the port you want
      - 1235:1235
    volumes:
      - /root/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
      - ./Blog.db:/App/Blog.db #SQlite datebase
      - /root/Project/BlazorBlog/aspnetapp.pfx:/App/aspnetapp.pfx #ssl certificate in PFX format
    environment:
      - ASPNETCORE_URLS=http://+:1234;https://+:1235  #Modified according to ports
      - ASPNETCORE_HTTPS_PORT=1235
      - ASPNETCORE_Kestrel__Certificates__Default__Password= #your certificate password 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/App/aspnetapp.pfx
      - ASPNETCORE_ENVIRONMENT=Production