services:
  dotnet:
    image: linkdotnet.blog.web
    build: ./
    container_name: dotnetBlog
    ports:
      - 80:80 #You can modify the port you want
      - 443:443
    volumes:
      - /root/Project/Blog/src/LinkDotNet.Blog.Web/appsettings.json:/app/appsettings.json
      - /root/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
      - ./Blog.db:/app/Blog.db #SQlite datebase
      - /root/aspnetapp.pfx:/app/aspnetapp.pfx #ssl certificate in PFX format
    environment:
      - ASPNETCORE_URLS=http://+:80;https://+:443 #Modified according to ports
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456 #your certificate password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - web_net
    depends_on:
      - sql
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    expose: 
      - 1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Hzs686868
    networks:
      - web_net
networks:
  web_net: