services:
  dotnet:
    image: mcr.microsoft.com/dotnet/aspnet:7.0
    container_name: dotnetBlog
    ports:
      - 5001:5001
      - 5000:5000
    volumes:
      - /home/HHH/Project/Blog/Publish:/App
      - /root/.aspnet/DataProtection-Keys
      - /home/HHH/Project/Blog/Blog.db
    working_dir: /App
    environment:
      - ASPNETCORE_URLS="http://localhost:5001;https://localhost:5002"
      - ASPNETCORE_ENVIRONMENT=Production
    entrypoint: dotnet ./LinkDotNet.Blog.Web.dll  